apiVersion: v1
kind: Deployment
metadata:
  name: Redis Event Listener
  namespace: redis
spec:
  containers:
  - name: Pona Redis Event Listener
    image: pona-redis-event-listener:latest
  environment:
    - name: REDIS_HOST
      value: redis-master.redis.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password
    - name: DB_HOST
      value: db-host
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: db-user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password