FROM oven/bun:1.2.9-alpine AS builder

WORKDIR /building
COPY . .
RUN bun install --production
RUN bun build

FROM node:23.11.0-alpine AS runner
WORKDIR /app
COPY --from=builder /building/dist ./dist
COPY --from=builder /building/node_modules ./node_modules
COPY --from=builder /building/package.json ./package.json

CMD [ "node", "./dist/index.js" ]